/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_conggroup_vizard_crypto_components_prf_PRF */

#ifndef _Included_org_conggroup_vizard_crypto_components_prf_PRF
#define _Included_org_conggroup_vizard_crypto_components_prf_PRF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_conggroup_vizard_crypto_components_prf_PRF
 * Method:    execGen
 * Signature: ([BJI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_conggroup_vizard_crypto_components_prf_PRF_execGen
        (JNIEnv *, jclass, jbyteArray, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
