/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_conggroup_vizard_crypto_components_dpf_DPF */

#ifndef _Included_org_conggroup_vizard_crypto_components_dpf_DPF
#define _Included_org_conggroup_vizard_crypto_components_dpf_DPF
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_conggroup_vizard_crypto_components_dpf_DPF
 * Method:    execGen
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_conggroup_vizard_crypto_components_dpf_DPF_execGen
        (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_conggroup_vizard_crypto_components_dpf_DPF
 * Method:    execEval
 * Signature: (J[B[B[BI)I
 */
JNIEXPORT jint JNICALL Java_org_conggroup_vizard_crypto_components_dpf_DPF_execEval
        (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
